### ISSUE TITLE
Adding Perma.cc to the list of archives

### ISSUE THREAD

**Issue by maturban** [oduwsdl/MemGator#104]
You may add **Perma.cc** to the list of archives:
TimeMap: `http://perma-archives.org/warc/timemap/*/`
TimeGate: `http://perma-archives.org/warc/timegate/`

**Comment by ibnesayeed** [comment]
It is [added already](https://github.com/oduwsdl/memgator/blob/gh-pages/archives.json) and being served when MemGator uses the [default archives list](http://git.io/archives). However, the sample `archives.json` file in the master branch does not have it noted there. We will keep this ticket open for tracking this issue, because soon we are planning to reorganize the repo that will not have duplicates to maintain which will solve it.

**Comment by ibnesayeed** [comment]
This can now be closed as we have unified the `archives.json` maintenance in #120 and removed the `gh-pages` branch.
