### ISSUE TITLE
perma.cc not included by default?

### ISSUE THREAD

**Issue by phonedude** [oduwsdl/MemGator#113]
https://perma-archives.org/warc/timegate/
https://perma-archives.org/warc/timemap/

**Comment by ibnesayeed** [comment]
I was added on Aug 31, 2016 via commit e414fbc8180dd0f04be01cba35b008e14719f3da. The `archives.json` file that is being served at https://git.io/archives is not the one in the `master` branch, but in the `gh-pages` branch. We have plans to unify that so that we do not have two copies of the file in the repo.
