### ISSUE TITLE
TimeGate/Map reported in one-off deployment even when not subsequently available

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/memgator#13]
I am not running the server instance in this case, but simply `memgator http://cnn.com/` returns

```sh
<http://cnn.com/>; rel="original",
<http://localhost:1208/timemap/link/http://cnn.com/>; rel="self"; type="application/link-format",
<http://wayback.vefsafn.is/wayback/20000620180259/http://cnn.com/>; rel="first memento"; datetime="Tue, 20 Jun 2000 18:02:59 GMT",
...
<http://web.archive.org/web/20151021124445/http://www.cnn.com>; rel="memento"; datetime="Wed, 21 Oct 2015 12:44:45 GMT",
<http://web.archive.org/web/20151021153520/http://www.cnn.com/>; rel="last memento"; datetime="Wed, 21 Oct 2015 15:35:20 GMT",
<http://localhost:1208/timemap/link/http://cnn.com/>; anchor="http://cnn.com/"; rel="timemap"; type="application/link-format",
<http://localhost:1208/timemap/json/http://cnn.com/>; anchor="http://cnn.com/"; rel="timemap"; type="application/json",
<http://localhost:1208/timemap/cdxj/http://cnn.com/>; anchor="http://cnn.com/"; rel="timemap"; type="application/cdxj+ors",
<http://localhost:1208/timegate/http://cnn.com/>; anchor="http://cnn.com/"; rel="timegate"
```

The last four URIs (pointing to `localhost`) are not available UNLESS the server instance is running. For one-off runs like the above, should we really report inaccessible TimeMaps and TimeGates? It seems inconsistent with the URI-Ms, which remain accessible even after the MemGator process finishes.

**Comment by ibnesayeed** [comment]
I thought about it when I was initially designing the workflow. It is not ideal, but I don't think it's a bug either. I decided to keep them there for two reasons:

* It makes the tooling for consuming the data simple that can work the same way irrespective of the data source whether it is coming from a server or the `STDOUT`, the format and expected attributes will be the same.
* It allows configuring an external default host where TimeMap and TimeGate services are actually running and the client can follow them if desired. It doesn't seem to be wrong to show a template (default localhost) URI for those services even if those URIs are inaccessible at the moment, because in HTTP world, advertising a URL does not require one to have it available.

However, there is a way around it that can be implemented if really seems useful and necessary. The idea is to introduce custom URI scheme to invoke shell command such as `cmd:URL%20Encoded%20command` or a more specific scheme such as `memgator:URL%20Encoded%20MemGator%20command` and then register `MemGator` to respond to that scheme.

**Comment by machawk1** [comment]
Adding a custom URI scheme seems like a big hammer and out of the scope of MemGator. Leaving the localhost references in should be a good default. I forgot about the ability to specify a TimeGate from the CLI, which would override these defaults.

**Comment by ibnesayeed** [comment]
Yes, the initial idea was to have a default service (running at ODU or LANL) hard-coded in the tool to advertise it, but due to the volatile nature of web services and longevity (of not being updated timely) of installed tools, I decided no to go that route and use `localhost` instead to educate users about the possibility of running a local service.

**Comment by machawk1** [comment]
What about adding some signifier to the localhost entries that were generated by default to indicate they they are placeholders? This is in similar vein of listing mementos that may not exist, which is expensive to generate but would make for more accurate TimeMaps. There does not appear to be a valid `rel` value to indicate this.

**Comment by ibnesayeed** [comment]
> What about adding some signifier to the localhost entries that were generated by default to indicate they they are placeholders?

The CLI would not no if a service is not (or will not be) running on localhost on that port. Hence the assumption that it is a placeholder may not be accurate.

**Comment by machawk1** [comment]
Closing this issue, chalking it up to "smart defaults" compared to the other solutions mentioned here.

**Comment by ibnesayeed** [comment]
There is a way to indicate the placeholder by using `example.com` as default instead of `localhost` in case of CLI, but that will force the user to pass the host information if a service is actually running or will be running on `localhost`. Additionally, the `example.com` will return a `200` response code, but not an expected media type. However, applications should be aware that `example.*` domain is for example purposes only.

**Comment by machawk1** [comment]
Let's keep with `localhost`.
