### ISSUE TITLE
Crossbuild script produces incomplete results with invalid architectures

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/MemGator#135]
Using latest master d2ef4cfd07e258cef92cabe214f290fab7c239e8

I am running `./crossbuild.sh`, which finishes with `cmd/go: unsupported GOOS/GOARCH pair darwin/386`. `/tmp/mgbins/` only contains memgator-linux-386 & memgator-linux-amd64 , which indicates that this error prematurely exited and/or did not build every permutation.

go version go1.16.3 darwin/amd64

EDIT: PR incoming.

**Comment by ibnesayeed** [comment]
Golang has been working on [removing support for darwin/386 for 1.15](https://github.com/golang/go/issues/37610) and above. I see very little value in building and releasing 32-bit binaries of any platforms, because the audience of this tool is likely using a 64 bit machine. That said, if one wants to build it for a peculiar OS/Arch combo, they can do so manually.
