### ISSUE TITLE
Report 0 mementos in the X-Mementos-Count header when none are found

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/memgator#38]
The current implementation returns a 404 but having this redundant information will allow cleaner logic in tools using MemGator.

**Comment by ibnesayeed** [comment]
It should not be difficult to add because the the decision of returning 404 is made based on the total count when it's zero. I have initially intentionally did not include it because it was returning 404 anyway. However, I agree that if a tool is only interested in the memento count, it will be a lot easier to always check just one thing and not add unnecessary conditionals to derive conclusion.

**Comment by ibnesayeed** [comment]
f51db8e6f7156fd7ca91d74c89c4d4503c808fd5 implements this and also limits the `X-Memento-Count` only to TimeMap requests.

**Comment by machawk1** [comment]
@ibnesayeed Has this been deployed at WS-DL? I still don't get the header:

```sh
curl -I http://memgator.cs.odu.edu:1208/timemap/json/matkelly.comxxxx
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Link, Location, X-Memento-Count, X-Generator
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
X-Generator: MemGator:1.0-rc2
Date: Wed, 04 Nov 2015 16:34:28 GMT
Content-Length: 19
```

**Comment by ibnesayeed** [comment]
No, it's not released yet, so not running on WSDL machine.

**Comment by machawk1** [comment]
Will this feature be provided in another RC or in the GM (1.0 proper)?

**Comment by ibnesayeed** [comment]
I think we will see more RCs before the stable release. The reason for that are some changes in the router and endpoint naming for the sake of similarity with the LANL service.

**Comment by machawk1** [comment]
:+1:
